name: vanvliet_sparse_k16
ndim: 2
window: 10
epochs: 100
warmup_epochs: 10
detection_folders:
  - TRA
input_train:
  - data/vanvliet/rpsM
  - data/vanvliet/recA
  - data/vanvliet/pheA
  - data/vanvliet/metA
  - data/vanvliet/cib
  - data/vanvliet/trpL
input_val:
  - data/vanvliet/rpsM
  - data/vanvliet/recA
  - data/vanvliet/pheA
outdir: runs
distributed: False
batch_size: 8
max_tokens: 8192
d_model: 256
num_encoder_layers: 4
num_decoder_layers: 4
pos_embed_per_dim: 32
feat_embed_per_dim: 8
dropout: 0.01
lr: 1e-4
features: wrfeat
causal_norm: quiet_softmax
attn_positional_bias: rope
spatial_pos_cutoff: 256
delta_cutoff: 2
knn_neighbors: 16
mixedp: True
num_workers: 8
seed: 42
augment: 3
